### ISSUE TITLE
Firefox Sync doesn't work

### ISSUE THREAD

**Issue by dimqua** [quindecim/fennec_user.js#1]
Please allow to easily enable syncing functionality, since it's not a privacy threat when using with your own server. A separate section with sync-related preferences could accomplish this.

**Comment by quindecim** [comment]
Hello, you can easily restore sync by opening my `user.js` file by putting `"// "` in front of these prefs:
```
user_pref("services.sync.enabled", false);
user_pref("webextensions.storage.sync.enabled", false);
user_pref("webextensions.storage.sync.serverURL", "");
user_pref("privacy.item.syncAccount", false);
```
Obviously if you had already applied `user.js` and you don't want to reinstall Fennec from scratch you have to browse to `about:config` and press "Reset" on the same prefs.

As for the order of the preferences slowly I'm rearranging everything. in the meantime, this small section can be found under "Miscellaneus", called "Disable sync".
