### ISSUE TITLE
Question regarding Webchannel URI

### ISSUE THREAD

**Issue by Atavic** [quindecim/fennec_user.js#2]
I see most of the URLs have been removed. :+1: But I also see that there's a URI still present:

>user_pref("identity.fxaccounts.remote.webchannel.uri", "https://0.0.0.0");

Why didn't you remove that one, too?

**Comment by quindecim** [comment]
Hi, because it is the cause of the faded settings on some devices if left blank.
so I opted for a local and fastest solution.

**Comment by Atavic** [comment]
Thank you. I bothered asking because I used something similar *127.0.0.1* but, upon reopening the browser, I found that a specific port was automatically added ---> *127.0.0.1:7999*

So I totally wipe most of these URLs entries. I suppose it is the system that added port 7999.
