### ISSUE TITLE
about:networking

### ISSUE THREAD

**Issue by Atavic** [quindecim/fennec_user.js#5]
Firefox Mobile and forks have some tools listed under *about:about* and
*about:networking* is useful for looking at startup connections.

I have only one listed: it's related to the only search engine that I left active (Wikipedia) because it cannot be disabled.

I block en.wikipedia.org on a [local VPN](https://github.com/IngoZenz/personaldnsfilter) and so I have no connections on startup.

I have removed [or substituted](https://github.com/quindecim/fennec_user.js/issues/2) all the URLs as [aus5.mozilla.org](https://github.com/quindecim/fennec_user.js/blob/master/user.js#L135) that still appeared as startup connection even if all update entries were set to false.

**Comment by quindecim** [comment]
I moved my repo at https://git.lelux.fi/quindecim/fennec_user.js
